services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8010
    ports:
      - "8010:8010"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
